[Interface]
Address = 192.168.6.67/32
DNS = 1.1.1.1,8.8.8.8
PrivateKey = WHyVoXLgbHYNP1NDz0k+t6VqLko2HhsfGs2bcMi8nWc=

[Peer]
PublicKey=L+0NHhvpjvj1wBlS20KM575NpcEXzbuDLwXGlCZJrmM=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = my1.vpnjantit.com:1024
