[Interface]
Address = 192.168.6.237/32
DNS = 1.1.1.1,8.8.8.8
PrivateKey = QJQ285Rjt1X1xDBJ/I4bEVsYI9RMBBzVjLH1uWyhsUQ=

[Peer]
PublicKey=i22ZBHxMIW3RJ5wWiqPKF/Npe8O5uAHNiYz7/SIRKiU=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = in10.vpnjantit.com:8888
